// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WWI.Models
{
    [Table("OrderLines", Schema = "Sales")]
    [Index(nameof(OrderId), Name = "FK_Sales_OrderLines_OrderID")]
    [Index(nameof(PackageTypeId), Name = "FK_Sales_OrderLines_PackageTypeID")]
    [Index(nameof(StockItemId), Name = "IX_Sales_OrderLines_AllocatedStockItems")]
    [Index(nameof(PickingCompletedWhen), nameof(OrderId), nameof(OrderLineId), Name = "IX_Sales_OrderLines_Perf_20160301_01")]
    [Index(nameof(StockItemId), nameof(PickingCompletedWhen), Name = "IX_Sales_OrderLines_Perf_20160301_02")]
    public partial class OrderLines
    {
        [Key]
        [Column("OrderLineID")]
        public int OrderLineId { get; set; }
        [Column("OrderID")]
        public int OrderId { get; set; }
        [Column("StockItemID")]
        public int StockItemId { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }
        [Column("PackageTypeID")]
        public int PackageTypeId { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? UnitPrice { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal TaxRate { get; set; }
        public int PickedQuantity { get; set; }
        public DateTime? PickingCompletedWhen { get; set; }
        public int LastEditedBy { get; set; }
        public DateTime LastEditedWhen { get; set; }

        [ForeignKey(nameof(LastEditedBy))]
        [InverseProperty(nameof(People.OrderLines))]
        public virtual People LastEditedByNavigation { get; set; }
        [ForeignKey(nameof(OrderId))]
        [InverseProperty(nameof(Orders.OrderLines))]
        public virtual Orders Order { get; set; }
        [ForeignKey(nameof(PackageTypeId))]
        [InverseProperty(nameof(PackageTypes.OrderLines))]
        public virtual PackageTypes PackageType { get; set; }
        [ForeignKey(nameof(StockItemId))]
        [InverseProperty(nameof(StockItems.OrderLines))]
        public virtual StockItems StockItem { get; set; }
    }
}